### ISSUE TITLE
Hub stop execute operation for stack with changed meta.name field

### ISSUE THREAD

**Issue by TheRealSpaceShip** [epam/hubctl#16]
If the user changes the` meta.name` field in the stack manifest hub will fail to execute an operation.

Steps
1. Deploy stack. For example <https://github.com/agilestacks/google-stacks/tree/main/terraform-example>
2. Change in `hub.yaml` value of `meta.name` from `Terraform example` to `Terraform example1`
3. Undeploy stack

AR: Hub failed with the message

```text
2022/07/01 09:13:10 State file does not match deployment manifest (elaborate):
        State meta.name = `Terraform example` does not match elaborate meta.name = `Terraform example1`
```

ER: hub should print a warning instead of fatal error and proceed with the operation

**Comment by akranga** [comment]
IMHO `hub` should allow to user override `meta.name`

When `--force` is a workaround

**Comment by arkadijs** [comment]
The original intent is a cheap safety net to prevent disasters if state file doesn't match manifest due to user error.

**Comment by akranga** [comment]
Closing this as rotten
