### ISSUE TITLE
Ubuntu documentation outdated

### ISSUE THREAD

**Issue by akranga** [epam/hubctl#36]
Landing website: superhub.io contains imprecise documentation on how to install hubctl for Linux. 

- [x] Ubuntu: update `apt-get ` instructions
- [x] Ubuntu: update `yq` instructions
- [x] Windows WSL: update `apt-get ` instructions
- [x] Windows WSL: update `yq` instructions
- [ ] Centos: add troubleshooting section for `mirror list` error
- [x] Centos: update `yq` instructions

**Comment by TheRealSpaceShip** [comment]
Obsolete. The landing website is https://hubctl.io and it has base installation instructions.
