### ISSUE TITLE
Replace git dependency with go-git library

### ISSUE THREAD

**Issue by TheRealSpaceShip** [epam/hubctl#38]
To remove `git` as a dependency tool we need to replace it with [go-git](https://github.com/go-git/go-git) library. A highly extensible Git implementation in pure Go.

This will improve UX, especially in bare minimal environments like [hub-toolbox](https://github.com/epam/hub-toolbox) or other custom docker images.

- [x] Change usage of git tool to go-git implementation
- [x] Write tests on new code

**Comment by oginskis** [comment]
Linked with #40
